void Fullscreen();
void SetConsoleColor();
void ClearConsole();
void go(int, int);
void CursorView(int);
void DrawTitle();
void DrawMenu();
void PrintCopyright();
int SelectMenu();
void ShowSelected(int);
void ShowLevel(int);
void ClearLevelInfo(int, int);
void NEWBIE(int, int);
void EASY(int, int);
void NORMAL(int, int);
void HARD(int, int);
void KOREAN(int, int);
void Play(int);
void MazeGenerator(int, int);
void ShowStartNEnd(int, int);
void MazeRunner();